/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Ensure the sw controls the page immediately
self.skipWaiting();
clientsClaim();

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);
cleanupOutdatedCaches();

// Handle incoming push notifications
self.addEventListener('push', function (event) {
  if (event.data) {
    try {
      const data = event.data.json();
      const title = data.title || 'New Notification';
      const options = {
        body: data.body || 'You have a new update.',
        icon: '/pwa-192x192.png',
        badge: '/maskable-icon-512x512.png',
        data: data, // contains action_url or other metadata
        vibrate: [100, 50, 100],
      };
      
      event.waitUntil(self.registration.showNotification(title, options));
    } catch (err) {
      console.error('Error parsing push data', err);
    }
  }
});

// Handle notification click
self.addEventListener('notificationclick', function (event) {
  event.notification.close();
  
  let actionUrl = event.notification.data?.action_url || '/';
  if (actionUrl && !actionUrl.startsWith('/') && !actionUrl.startsWith('http')) {
    actionUrl = '/' + actionUrl;
  }

  // This looks to see if the current window is already open and
  // focuses if it is
  event.waitUntil(
    clients.matchAll({ type: 'window' }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(self.registration.scope) && 'focus' in client) {
          client.focus();
          // Optionally send a message to the client to navigate to actionUrl
          client.postMessage({ type: 'NAVIGATE', url: actionUrl });
          return;
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(actionUrl);
      }
    })
  );
});
